Repository celestiaorg/go-square, pull requests merged in 2024-10, with the labels that each got.

#106 chore: expose generate subtree roots method
  inclusion/commitment.go
Labels: chore

#107 chore: add fmt target to makefile and fix linting
  Makefile
  share/share_builder_test.go
Labels: chore

#115 chore: add idea folder to gitignore
  .gitignore
Labels: external, chore

#109 feat: add missing utilities used by celestia-node
  share/blob.go
  share/blob_test.go
  share/namespace.go
  share/namespace_test.go
  share/parse_sparse_shares_test.go
  share/random_blobs.go
  share/random_namespace.go
  share/random_shares.go
  share/share.go
  share/share_test.go
Labels: external
